name: Deploy static content to ftp server

on:
  push:
    branches: ["master"]

  workflow_dispatch:

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: ftp-deplyoment
    runs-on: ubuntu-latest
    steps:
      - name: FTP Deployment
        # You may pin to the exact commit or the version.
        # uses: airvzxf/ftp-deployment-action@9efe025c218094bd451a0cb684d7cb471f4d9d4f
        uses: airvzxf/ftp-deployment-action@latest
        with:
          server: ttvbuehlertal.de
          user: 'empty'
          password: 'empty'
          # Delete all the files inside of the remote directory.
          delete: true # optional, default is false
